spring:
  datasource:
    url: jdbc:mysql://124.70.206.207:3306/javaee?serverTimezone=GMT%2B8
    username: javaee
    password: 666666wW
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    default-encoding: utf-8
    port: 25
    host: smtp.163.com
    protocol: smtp
    username: TJzengle@163.com
    password: KZQVRNDUKHIMJDVK
  mvc:
    static-path-pattern: /static/**

expiredTime:
  300000
